version: "3"\\
services:\\
  web:\\
    image: nemarci/get-started:part2\\
    deploy:\\
      replicas: 5\\
      resources:\\
        limits:\\
          cpus: "0.1"\\
          memory: 50M\\
      restart\_policy:\\
        condition: on-failure\\
    ports:\\
      - "80:80"\\
    networks:\\
      - webnet\\
networks:\\
  webnet:\\
